import ply.lex as lex

reserved = [
    "ADD",
    "EXTERNAL",
    "PROCEDURE",
    "ALL",
    "FETCH",
    "PUBLIC",
    "ALTER",
    "FILE",
    "RAISERROR",
    "AND",
    "FILLFACTOR",
    "READ",
    "ANY",
    "FOR",
    "READTEXT",
    "AS",
    "FOREIGN",
    "RECONFIGURE",
    "ASC",
    "FREETEXT",
    "REFERENCES",
    "AUTHORIZATION",
    "FREETEXTTABLE",
    "REPLICATION",
    "BACKUP",
    "FROM",
    "RESTORE",
    "BEGIN",
    "FULL",
    "RESTRICT",
    "BETWEEN",
    "FUNCTION",
    "RETURN",
    "BREAK",
    "GOTO",
    "REVERT",
    "BROWSE",
    "GRANT",
    "REVOKE",
    "BULK",
    "GROUP",
    "RIGHT",
    "BY",
    "HAVING",
    "ROLLBACK",
    "CASCADE",
    "HOLDLOCK",
    "ROWCOUNT",
    "CASE",
    "IDENTITY",
    "ROWGUIDCOL",
    "CHECK",
    "IDENTITY_INSERT",
    "RULE",
    "CHECKPOINT",
    "IDENTITYCOL",
    "SAVE",
    "CLOSE",
    "IF",
    "SCHEMA",
    "CLUSTERED",
    "IN",
    "SECURITYAUDIT",
    "COALESCE",
    "INDEX",
    "SELECT",
    "COLLATE",
    "INNER",
    "SEMANTICKEYPHRASETABLE",
    "COLUMN",
    "INSERT",
    "SEMANTICSIMILARITYDETAILSTABLE",
    "COMMIT",
    "INTERSECT",
    "SEMANTICSIMILARITYTABLE",
    "COMPUTE",
    "INTO",
    "SESSION_USER",
    "CONSTRAINT",
    "IS",
    "SET",
    "CONTAINS",
    "JOIN",
    "SETUSER",
    "CONTAINSTABLE",
    "KEY",
    "SHUTDOWN",
    "CONTINUE",
    "KILL",
    "SOME",
    "CONVERT",
    "LEFT",
    "STATISTICS",
    "CREATE",
    "LIKE",
    "SYSTEM_USER",
    "CROSS",
    "LINENO",
    "TABLE",
    "CURRENT",
    "LOAD",
    "TABLESAMPLE",
    "CURRENT_DATE",
    "MERGE",
    "TEXTSIZE",
    "CURRENT_TIME",
    "NATIONAL",
    "THEN",
    "CURRENT_TIMESTAMP",
    "NOCHECK",
    "TO",
    "CURRENT_USER",
    "NONCLUSTERED",
    "TOP",
    "CURSOR",
    "NOT",
    "TRAN",
    "DATABASE",
    "NULL",
    "TRANSACTION",
    "DBCC",
    "NULLIF",
    "TRIGGER",
    "DEALLOCATE",
    "OF",
    "TRUNCATE",
    "DECLARE",
    "OFF",
    "TRY_CONVERT",
    "DEFAULT",
    "OFFSETS",
    "TSEQUAL",
    "DELETE",
    "ON",
    "UNION",
    "DENY",
    "OPEN",
    "UNIQUE",
    "DESC",
    "UNPIVOT",
    "DISK",
    "OPENQUERY",
    "UPDATE",
    "DISTINCT",
    "OPENROWSET",
    "UPDATETEXT",
    "DISTRIBUTED",
    "OPENXML",
    "USE",
    "DOUBLE",
    "OPTION",
    "USER",
    "DROP",
    "OR",
    "VALUES",
    "DUMP",
    "ORDER",
    "VARYING",
    "ELSE",
    "OUTER",
    "VIEW",
    "END",
    "OVER",
    "WAITFOR",
    "ERRLVL",
    "PERCENT",
    "WHEN",
    "ESCAPE",
    "PIVOT",
    "WHERE",
    "EXCEPT",
    "PLAN",
    "WHILE",
    "EXEC",
    "PRECISION",
    "WITH",
    "EXECUTE",
    "PRIMARY",
    "EXISTS",
    "PRINT",
    "WRITETEXT",
    "EXIT",
    "PROC",
    "EXCEPTION",
    "ABSOLUTE",
    "OVERLAPS",
    "ACTION",
    "ADA",
    "PARTIAL",
    "PASCAL",
    "EXTRACT",
    "POSITION",
    "ALLOCATE",
    "FALSE",
    "PREPARE",
    "FIRST",
    "PRESERVE",
    "FLOAT",
    "ARE",
    "PRIOR",
    "FORTRAN",
    "ASSERTION",
    "FOUND",
    "AT",
    "REAL",
    "AVG",
    "GET",
    "GLOBAL",
    "RELATIVE",
    "BIT",
    "BIT_LENGTH",
    "BOTH",
    "HOUR",
    "CASCADED",
    "SCROLL",
    "IMMEDIATE",
    "SECOND",
    "CAST",
    "SECTION",
    "CATALOG",
    "INCLUDE",
    "CHAR",
    "SESSION",
    "CHAR_LENGTH",
    "CHARACTER",
    "INITIALLY",
    "CHARACTER_LENGTH",
    "SIZE",
    "INPUT",
    "SMALLINT",
    "INSENSITIVE",
    "SPACE",
    "INT",
    "SQL",
    "COLLATION",
    "INTEGER",
    "SQLCA",
    "SQLCODE",
    "SQLERROR",
    "CONNECT",
    "SQLSTATE",
    "CONNECTION",
    "SQLWARNING",
    "ISOLATION",
    "SUBSTRING",
    "CONSTRAINTS",
    "SUM",
    "LANGUAGE",
    "CORRESPONDING",
    "LAST",
    "TEMPORARY",
    "COUNT",
    "LEADING",
    "LEVEL",
    "TIMESTAMP",
    "TIME",
    "TIMEZONE_HOUR",
    "TIMEZONE_MINUTE",
    "LOCAL",
    "LOWER",
    "MATCH",
    "TRAILING",
    "MAX",
    "MIN",
    "TRANSLATE",
    "DATE",
    "MINUTE",
    "MONTH",
    "TRUE",
    "DEC",
    "NAMES",
    "DECIMAL",
    "NATURAL",
    "UNKNOWN",
    "NCHAR",
    "DEFERRABLE",
    "NEXT",
    "UPPER",
    "DEFERRED",
    "NO",
    "USAGE",
    "NONE",
    "DESCRIBE",
    "NUMERIC",
    "VARCHAR",
    "DISCONNECT",
    "OCTET_LENGTH",
    "ONLY",
    "WHENEVER",
    "WORK",
    "VALUE",
    "DESCRIPTOR",
    "DOMAIN",
    "WRITE",
    "OUTPUT",
    "ZONE",
    "TRANSLATION",
]


tokens = [
    # + - * / % ^
    "PLUS",
    "MINUS",
    "TIMES",
    "DIVIDE",
    "MOD",
    "POWER",
    # ( ) [ ] { }
    "LPAREN",
    "RPAREN",
    "LBRACKET",
    "RBRACKET",
    "LBRACE",
    "RBRACE",
    # = '!= | <>' < <= > >=
    "EQUAL",
    "NOT_EQUAL",
    "LESS_THAN",
    "LESS_EQUAL",
    "GREATER_THAN",
    "GREATER_EQUAL",
    # Identifiers
    "ID",
    # , ; .
    "COMMA",
    "SEMICOLON",
    "DOT",
] + reserved

t_PLUS = r'\+'
t_MINUS = r'-'
t_TIMES = r'\*'
t_DIVIDE = r'/'
t_MOD = r'%'
t_POWER = r'\^'
t_ignore = ' \t'

def t_ID(t):
    r'[A-Za-z_][A-Za-z0-9_]*|\[[^\]]+\]'
    t.type = t.value if t.value in reserved else 'ID'
    return t

def t_newline(t):
   r'\n+'
   t.lexer.lineno += len(t.value)
   
def t_error(t):
   print("Illegal character '%s'" % t.value[0])
   t.lexer.skip(1)

def main():
    file = open("test.sql", "r")
    lexer = lex.lex()
    lexer.input(file.read())
    print('\n# lexer output:\n')
    for tok in lexer:
        print('type:', tok.type,', value:',tok.value,", line:", tok.lineno,", column: ", tok.lexpos + 1)

    print()

if __name__ == "__main__":
    main()
