
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COMMA CREATE DATABASE DEFAULT DELETE DIVIDE DOT DROP EQUAL FROM GREATER_EQUAL GREATER_THAN ID IDENTITY INSERT INT INTO IS KEY LBRACE LBRACKET LESS_EQUAL LESS_THAN LPAREN MINUS MOD NOT NOT_EQUAL NULL PLUS POWER PRIMARY RBRACE RBRACKET RPAREN SELECT SEMICOLON SET STRING TABLE TIMES TRUNCATE UNIQUE UPDATE VALUES WHEREscript : script : command SEMICOLON scriptcommand : TRUNCATE TABLE objectcommand : CREATE DATABASE objecttype : INT\n| STRINGobject : IDobject : ID DOT IDobject : ID DOT ID DOT ID'
    
_lr_action_items = {'$end':([0,1,5,8,],[-1,0,-1,-2,]),'TRUNCATE':([0,5,],[3,3,]),'CREATE':([0,5,],[4,4,]),'SEMICOLON':([2,9,10,11,13,15,],[5,-3,-7,-4,-8,-9,]),'TABLE':([3,],[6,]),'DATABASE':([4,],[7,]),'ID':([6,7,12,14,],[10,10,13,15,]),'DOT':([10,13,],[12,14,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'script':([0,5,],[1,8,]),'command':([0,5,],[2,2,]),'object':([6,7,],[9,11,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> script","S'",1,None,None,None),
  ('script -> <empty>','script',0,'p_script_empty','sintatico.py',6),
  ('script -> command SEMICOLON script','script',3,'p_script_compound','sintatico.py',10),
  ('command -> TRUNCATE TABLE object','command',3,'p_command_truncate','sintatico.py',14),
  ('command -> CREATE DATABASE object','command',3,'p_command_create_database','sintatico.py',18),
  ('type -> INT','type',1,'p_type','sintatico.py',24),
  ('type -> STRING','type',1,'p_type','sintatico.py',25),
  ('object -> ID','object',1,'p_object_id','sintatico.py',29),
  ('object -> ID DOT ID','object',3,'p_object_schema','sintatico.py',33),
  ('object -> ID DOT ID DOT ID','object',5,'p_object_db_schema','sintatico.py',37),
]
