CREATE DATABASE EMP_CL;

SELECT * FROM FUNCIONARIO;

SELECT NOME, SALARIO FUNCIONARIO;

TRUNCATE TABLE ENDERECO_FUNC;

DELETE FROM ENDERECO_FUNC;

DELETE FROM ENDERECO_FUNC WHERE CREATED_AT = '20250-12-01';

DROP DATABASE EMP_CG;

INSERT INTO FUNCIONARIO 
VALUES ('Felipe', '06548213422', 2, 3, 4, 4, 4, NULL, NULL);

INSERT INTO FUNCIONARIO (nome, cpf, id_salario, id_endereco, id_telefone, id_bonificacao, id_ferias) 
VALUES ('Felipe', '06548213422', 2, 3, 4, 4, 4, NULL, NULL);

UPDATE FUNCIONARIO
SET nome = 'Diogo'
WHERE id = 42;

UPDATE FUNCIONARIO
SET nome = 'Diogo';


