INSERT INTO FUNC (ID, NOME, SALARIO) VALUES (1, 'Felipe', 3500);

INSERT INTO FUNC
VALUES (1, 'Felipe', 3500);

SELECT A, B, C FROM TABELA;

-- UPDATE FUNCIONARIO SET nome = 'Felipe', idade = 25;

-- UPDATE FUNCIONARIO SET nome = 'Felipe' WHERE id = 10;


-- L4M0D WAS HERE

/*
    zBro too.
*/
